### ISSUE TITLE
seg fault after running multiple models within the same program

### ISSUE THREAD

**Issue by Kuan-ChiehHsu** [Namburger/edgetpu-minimal-example#6]
Hi, I have encountered an seg fault on my modified version of this repo. Basically what I'm trying to change is to run two separated models within the same program sequentially. There are two interpreters to handle them separately. I got the following gdb trace where it stocks at the moment when retrieving output data after second model's inferencing. 

I'm wondering if such scenario has been tested or not, and it might help me to understand what is the root cause of the seg fault in my situation.
Thanks!

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055a5a7cfc03f in std::vector<std::unique_ptr<tflite::Subgraph, std::default_delete<tflite::Subgraph> >, std::allocator<std::unique_ptr<tflite::Subgraph, std::default_delete<tflite::Subgraph> > > >::begin() const ()
[Current thread is 1 (Thread 0x7f82fc180780 (LWP 2733))]
(gdb) bt
#0  0x000055a5a7cfc03f in std::vector<std::unique_ptr<tflite::Subgraph, std::default_delete<tflite::Subgraph> >, std::allocator<std::unique_ptr<tflite::Subgraph, std::default_delete<tflite::Subgraph> > > >::begin() const ()
#1  0x000055a5a7cfaeed in std::vector<std::unique_ptr<tflite::Subgraph, std::default_delete<tflite::Subgraph> >, std::allocator<std::unique_ptr<tflite::Subgraph, std::default_delete<tflite::Subgraph> > > >::front() const ()
#2  0x000055a5a7cfa72e in tflite::Interpreter::primary_subgraph() const ()
#3  0x000055a5a7cfa676 in tflite::Interpreter::outputs() const ()
```

**Comment by Kuan-ChiehHsu** [comment]
It was because I tried to access the output data of the second inferencing from the **first** interpreter, not the **second** one that it should be. It's solved now.
